@OrderService_HostAddress = http://localhost:5064

### Create a new order
POST {{OrderService_HostAddress}}/orders/
Content-Type: application/json

{
  "customer": "John Doe",
  "total": 149.99,
  "status": "Pending"
}

###

### Get all orders
GET {{OrderService_HostAddress}}/orders/
Accept: application/json

###

### Get order by ID
GET {{OrderService_HostAddress}}/orders/1
Accept: application/json

###

### Update an order
PUT {{OrderService_HostAddress}}/orders/1
Content-Type: application/json

{
  "id": 1,
  "customer": "John Doe",
  "total": 199.99,
  "status": "Processing",
  "createdAt": "2025-07-08T00:00:00Z"
}

###

### Delete an order
DELETE {{OrderService_HostAddress}}/orders/1